//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.PrevisionSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrevisionEnt", Namespace="http://schemas.datacontract.org/2004/07/CentroMedico.Datos")]
    [System.SerializableAttribute()]
    public partial class PrevisionEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prevision_descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prevision_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prevision_desc {
            get {
                return this.prevision_descField;
            }
            set {
                if ((object.ReferenceEquals(this.prevision_descField, value) != true)) {
                    this.prevision_descField = value;
                    this.RaisePropertyChanged("prevision_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prevision_id {
            get {
                return this.prevision_idField;
            }
            set {
                if ((object.ReferenceEquals(this.prevision_idField, value) != true)) {
                    this.prevision_idField = value;
                    this.RaisePropertyChanged("prevision_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrevisionSvc.IPrevision")]
    public interface IPrevision {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevision/InsertarPrevision", ReplyAction="http://tempuri.org/IPrevision/InsertarPrevisionResponse")]
        bool InsertarPrevision(ConsoleApplication1.PrevisionSvc.PrevisionEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevision/InsertarPrevision", ReplyAction="http://tempuri.org/IPrevision/InsertarPrevisionResponse")]
        System.Threading.Tasks.Task<bool> InsertarPrevisionAsync(ConsoleApplication1.PrevisionSvc.PrevisionEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevision/ObtenerPrevision", ReplyAction="http://tempuri.org/IPrevision/ObtenerPrevisionResponse")]
        string ObtenerPrevision();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevision/ObtenerPrevision", ReplyAction="http://tempuri.org/IPrevision/ObtenerPrevisionResponse")]
        System.Threading.Tasks.Task<string> ObtenerPrevisionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrevisionChannel : ConsoleApplication1.PrevisionSvc.IPrevision, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrevisionClient : System.ServiceModel.ClientBase<ConsoleApplication1.PrevisionSvc.IPrevision>, ConsoleApplication1.PrevisionSvc.IPrevision {
        
        public PrevisionClient() {
        }
        
        public PrevisionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrevisionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrevisionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrevisionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarPrevision(ConsoleApplication1.PrevisionSvc.PrevisionEnt entidad) {
            return base.Channel.InsertarPrevision(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarPrevisionAsync(ConsoleApplication1.PrevisionSvc.PrevisionEnt entidad) {
            return base.Channel.InsertarPrevisionAsync(entidad);
        }
        
        public string ObtenerPrevision() {
            return base.Channel.ObtenerPrevision();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPrevisionAsync() {
            return base.Channel.ObtenerPrevisionAsync();
        }
    }
}
