//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedicoWeb.AgendaSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgendaEnt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AgendaEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_fecha_terminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_medico_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string agenda_id {
            get {
                return this.agenda_idField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_idField, value) != true)) {
                    this.agenda_idField = value;
                    this.RaisePropertyChanged("agenda_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agenda_fecha_inicio {
            get {
                return this.agenda_fecha_inicioField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_fecha_inicioField, value) != true)) {
                    this.agenda_fecha_inicioField = value;
                    this.RaisePropertyChanged("agenda_fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string agenda_fecha_termino {
            get {
                return this.agenda_fecha_terminoField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_fecha_terminoField, value) != true)) {
                    this.agenda_fecha_terminoField = value;
                    this.RaisePropertyChanged("agenda_fecha_termino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string agenda_medico_id {
            get {
                return this.agenda_medico_idField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_medico_idField, value) != true)) {
                    this.agenda_medico_idField = value;
                    this.RaisePropertyChanged("agenda_medico_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgendaSvc.IAgenda")]
    public interface IAgenda {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerAgendaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/ObtenerAgenda", ReplyAction="http://tempuri.org/IAgenda/ObtenerAgendaResponse")]
        CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponse ObtenerAgenda(CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/ObtenerAgenda", ReplyAction="http://tempuri.org/IAgenda/ObtenerAgendaResponse")]
        System.Threading.Tasks.Task<CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponse> ObtenerAgendaAsync(CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento entidad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/InsertarAgenda", ReplyAction="http://tempuri.org/IAgenda/InsertarAgendaResponse")]
        CentroMedicoWeb.AgendaSvc.InsertarAgendaResponse InsertarAgenda(CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/InsertarAgenda", ReplyAction="http://tempuri.org/IAgenda/InsertarAgendaResponse")]
        System.Threading.Tasks.Task<CentroMedicoWeb.AgendaSvc.InsertarAgendaResponse> InsertarAgendaAsync(CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAgendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAgenda", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequestBody Body;
        
        public ObtenerAgendaRequest() {
        }
        
        public ObtenerAgendaRequest(CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerAgendaRequestBody {
        
        public ObtenerAgendaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAgendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAgendaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponseBody Body;
        
        public ObtenerAgendaResponse() {
        }
        
        public ObtenerAgendaResponse(CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerAgendaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerAgendaResult;
        
        public ObtenerAgendaResponseBody() {
        }
        
        public ObtenerAgendaResponseBody(string ObtenerAgendaResult) {
            this.ObtenerAgendaResult = ObtenerAgendaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAgendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAgenda", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedicoWeb.AgendaSvc.InsertarAgendaRequestBody Body;
        
        public InsertarAgendaRequest() {
        }
        
        public InsertarAgendaRequest(CentroMedicoWeb.AgendaSvc.InsertarAgendaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAgendaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CentroMedicoWeb.AgendaSvc.AgendaEnt entidad;
        
        public InsertarAgendaRequestBody() {
        }
        
        public InsertarAgendaRequestBody(CentroMedicoWeb.AgendaSvc.AgendaEnt entidad) {
            this.entidad = entidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAgendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAgendaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedicoWeb.AgendaSvc.InsertarAgendaResponseBody Body;
        
        public InsertarAgendaResponse() {
        }
        
        public InsertarAgendaResponse(CentroMedicoWeb.AgendaSvc.InsertarAgendaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAgendaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarAgendaResult;
        
        public InsertarAgendaResponseBody() {
        }
        
        public InsertarAgendaResponseBody(bool InsertarAgendaResult) {
            this.InsertarAgendaResult = InsertarAgendaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgendaChannel : CentroMedicoWeb.AgendaSvc.IAgenda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgendaClient : System.ServiceModel.ClientBase<CentroMedicoWeb.AgendaSvc.IAgenda>, CentroMedicoWeb.AgendaSvc.IAgenda {
        
        public AgendaClient() {
        }
        
        public AgendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponse CentroMedicoWeb.AgendaSvc.IAgenda.ObtenerAgenda(CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest request) {
            return base.Channel.ObtenerAgenda(request);
        }
        
        public string ObtenerAgenda() {
            CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest inValue = new CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest();
            inValue.Body = new CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequestBody();
            CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponse retVal = ((CentroMedicoWeb.AgendaSvc.IAgenda)(this)).ObtenerAgenda(inValue);
            return retVal.Body.ObtenerAgendaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponse> CentroMedicoWeb.AgendaSvc.IAgenda.ObtenerAgendaAsync(CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest request) {
            return base.Channel.ObtenerAgendaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedicoWeb.AgendaSvc.ObtenerAgendaResponse> ObtenerAgendaAsync() {
            CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest inValue = new CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequest();
            inValue.Body = new CentroMedicoWeb.AgendaSvc.ObtenerAgendaRequestBody();
            return ((CentroMedicoWeb.AgendaSvc.IAgenda)(this)).ObtenerAgendaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedicoWeb.AgendaSvc.InsertarAgendaResponse CentroMedicoWeb.AgendaSvc.IAgenda.InsertarAgenda(CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest request) {
            return base.Channel.InsertarAgenda(request);
        }
        
        public bool InsertarAgenda(CentroMedicoWeb.AgendaSvc.AgendaEnt entidad) {
            CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest inValue = new CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest();
            inValue.Body = new CentroMedicoWeb.AgendaSvc.InsertarAgendaRequestBody();
            inValue.Body.entidad = entidad;
            CentroMedicoWeb.AgendaSvc.InsertarAgendaResponse retVal = ((CentroMedicoWeb.AgendaSvc.IAgenda)(this)).InsertarAgenda(inValue);
            return retVal.Body.InsertarAgendaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedicoWeb.AgendaSvc.InsertarAgendaResponse> CentroMedicoWeb.AgendaSvc.IAgenda.InsertarAgendaAsync(CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest request) {
            return base.Channel.InsertarAgendaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedicoWeb.AgendaSvc.InsertarAgendaResponse> InsertarAgendaAsync(CentroMedicoWeb.AgendaSvc.AgendaEnt entidad) {
            CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest inValue = new CentroMedicoWeb.AgendaSvc.InsertarAgendaRequest();
            inValue.Body = new CentroMedicoWeb.AgendaSvc.InsertarAgendaRequestBody();
            inValue.Body.entidad = entidad;
            return ((CentroMedicoWeb.AgendaSvc.IAgenda)(this)).InsertarAgendaAsync(inValue);
        }
    }
}
