//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Mvc.RegistroSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistroSvc.IRegistro")]
    public interface IRegistro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/LoginUsuario", ReplyAction="http://tempuri.org/IRegistro/LoginUsuarioResponse")]
        CentroMedico.Datos.RegistroEnt LoginUsuario(string usuario, string contrass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/LoginUsuario", ReplyAction="http://tempuri.org/IRegistro/LoginUsuarioResponse")]
        System.Threading.Tasks.Task<CentroMedico.Datos.RegistroEnt> LoginUsuarioAsync(string usuario, string contrass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistroChannel : CentroMedico.Mvc.RegistroSvc.IRegistro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistroClient : System.ServiceModel.ClientBase<CentroMedico.Mvc.RegistroSvc.IRegistro>, CentroMedico.Mvc.RegistroSvc.IRegistro {
        
        public RegistroClient() {
        }
        
        public RegistroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CentroMedico.Datos.RegistroEnt LoginUsuario(string usuario, string contrass) {
            return base.Channel.LoginUsuario(usuario, contrass);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Datos.RegistroEnt> LoginUsuarioAsync(string usuario, string contrass) {
            return base.Channel.LoginUsuarioAsync(usuario, contrass);
        }
    }
}
