//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Mvc.SucursalesSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SucursalesSvc.ISucursales")]
    public interface ISucursales {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/ObtenerSucursales", ReplyAction="http://tempuri.org/ISucursales/ObtenerSucursalesResponse")]
        string ObtenerSucursales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/ObtenerSucursales", ReplyAction="http://tempuri.org/ISucursales/ObtenerSucursalesResponse")]
        System.Threading.Tasks.Task<string> ObtenerSucursalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/InsertarSucursal", ReplyAction="http://tempuri.org/ISucursales/InsertarSucursalResponse")]
        bool InsertarSucursal(CentroMedico.Datos.SucursalEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/InsertarSucursal", ReplyAction="http://tempuri.org/ISucursales/InsertarSucursalResponse")]
        System.Threading.Tasks.Task<bool> InsertarSucursalAsync(CentroMedico.Datos.SucursalEnt entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISucursalesChannel : CentroMedico.Mvc.SucursalesSvc.ISucursales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SucursalesClient : System.ServiceModel.ClientBase<CentroMedico.Mvc.SucursalesSvc.ISucursales>, CentroMedico.Mvc.SucursalesSvc.ISucursales {
        
        public SucursalesClient() {
        }
        
        public SucursalesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SucursalesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SucursalesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SucursalesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerSucursales() {
            return base.Channel.ObtenerSucursales();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerSucursalesAsync() {
            return base.Channel.ObtenerSucursalesAsync();
        }
        
        public bool InsertarSucursal(CentroMedico.Datos.SucursalEnt entidad) {
            return base.Channel.InsertarSucursal(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarSucursalAsync(CentroMedico.Datos.SucursalEnt entidad) {
            return base.Channel.InsertarSucursalAsync(entidad);
        }
    }
}
