//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Reserva {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaEnt", Namespace="http://schemas.datacontract.org/2004/07/CentroMedico.Datos")]
    [System.SerializableAttribute()]
    public partial class ReservaEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_agenda_detalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_especialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_horaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_medicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_paciente_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_paciente_rutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_previsionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_sucursalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_agenda_detalle {
            get {
                return this.reserva_agenda_detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_agenda_detalleField, value) != true)) {
                    this.reserva_agenda_detalleField = value;
                    this.RaisePropertyChanged("reserva_agenda_detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_especialidad {
            get {
                return this.reserva_especialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_especialidadField, value) != true)) {
                    this.reserva_especialidadField = value;
                    this.RaisePropertyChanged("reserva_especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_fecha {
            get {
                return this.reserva_fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_fechaField, value) != true)) {
                    this.reserva_fechaField = value;
                    this.RaisePropertyChanged("reserva_fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_hora {
            get {
                return this.reserva_horaField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_horaField, value) != true)) {
                    this.reserva_horaField = value;
                    this.RaisePropertyChanged("reserva_hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_id {
            get {
                return this.reserva_idField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_idField, value) != true)) {
                    this.reserva_idField = value;
                    this.RaisePropertyChanged("reserva_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_medico {
            get {
                return this.reserva_medicoField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_medicoField, value) != true)) {
                    this.reserva_medicoField = value;
                    this.RaisePropertyChanged("reserva_medico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_paciente_nombre {
            get {
                return this.reserva_paciente_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_paciente_nombreField, value) != true)) {
                    this.reserva_paciente_nombreField = value;
                    this.RaisePropertyChanged("reserva_paciente_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_paciente_rut {
            get {
                return this.reserva_paciente_rutField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_paciente_rutField, value) != true)) {
                    this.reserva_paciente_rutField = value;
                    this.RaisePropertyChanged("reserva_paciente_rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_prevision {
            get {
                return this.reserva_previsionField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_previsionField, value) != true)) {
                    this.reserva_previsionField = value;
                    this.RaisePropertyChanged("reserva_prevision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_sucursal {
            get {
                return this.reserva_sucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_sucursalField, value) != true)) {
                    this.reserva_sucursalField = value;
                    this.RaisePropertyChanged("reserva_sucursal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Reserva.IReserva")]
    public interface IReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/InsertarReserva", ReplyAction="http://tempuri.org/IReserva/InsertarReservaResponse")]
        bool InsertarReserva(ConsoleApplication1.Reserva.ReservaEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/InsertarReserva", ReplyAction="http://tempuri.org/IReserva/InsertarReservaResponse")]
        System.Threading.Tasks.Task<bool> InsertarReservaAsync(ConsoleApplication1.Reserva.ReservaEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraDatoReserva", ReplyAction="http://tempuri.org/IReserva/MuestraDatoReservaResponse")]
        ConsoleApplication1.Reserva.ReservaEnt MuestraDatoReserva(string c_esp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraDatoReserva", ReplyAction="http://tempuri.org/IReserva/MuestraDatoReservaResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.Reserva.ReservaEnt> MuestraDatoReservaAsync(string c_esp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraListaTodasLasReservasRealizadas", ReplyAction="http://tempuri.org/IReserva/MuestraListaTodasLasReservasRealizadasResponse")]
        string MuestraListaTodasLasReservasRealizadas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraListaTodasLasReservasRealizadas", ReplyAction="http://tempuri.org/IReserva/MuestraListaTodasLasReservasRealizadasResponse")]
        System.Threading.Tasks.Task<string> MuestraListaTodasLasReservasRealizadasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/ListaTodosLosPacientesEnEspera", ReplyAction="http://tempuri.org/IReserva/ListaTodosLosPacientesEnEsperaResponse")]
        string ListaTodosLosPacientesEnEspera();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/ListaTodosLosPacientesEnEspera", ReplyAction="http://tempuri.org/IReserva/ListaTodosLosPacientesEnEsperaResponse")]
        System.Threading.Tasks.Task<string> ListaTodosLosPacientesEnEsperaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraPacientesEsperaXdoctor", ReplyAction="http://tempuri.org/IReserva/MuestraPacientesEsperaXdoctorResponse")]
        string MuestraPacientesEsperaXdoctor(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraPacientesEsperaXdoctor", ReplyAction="http://tempuri.org/IReserva/MuestraPacientesEsperaXdoctorResponse")]
        System.Threading.Tasks.Task<string> MuestraPacientesEsperaXdoctorAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraListaDeReservaXpaciente", ReplyAction="http://tempuri.org/IReserva/MuestraListaDeReservaXpacienteResponse")]
        string MuestraListaDeReservaXpaciente(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/MuestraListaDeReservaXpaciente", ReplyAction="http://tempuri.org/IReserva/MuestraListaDeReservaXpacienteResponse")]
        System.Threading.Tasks.Task<string> MuestraListaDeReservaXpacienteAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/CambiarEstadoPaciente", ReplyAction="http://tempuri.org/IReserva/CambiarEstadoPacienteResponse")]
        bool CambiarEstadoPaciente(ConsoleApplication1.Reserva.ReservaEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/CambiarEstadoPaciente", ReplyAction="http://tempuri.org/IReserva/CambiarEstadoPacienteResponse")]
        System.Threading.Tasks.Task<bool> CambiarEstadoPacienteAsync(ConsoleApplication1.Reserva.ReservaEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/CambiarEstadoPacienteEspera", ReplyAction="http://tempuri.org/IReserva/CambiarEstadoPacienteEsperaResponse")]
        bool CambiarEstadoPacienteEspera(ConsoleApplication1.Reserva.ReservaEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReserva/CambiarEstadoPacienteEspera", ReplyAction="http://tempuri.org/IReserva/CambiarEstadoPacienteEsperaResponse")]
        System.Threading.Tasks.Task<bool> CambiarEstadoPacienteEsperaAsync(ConsoleApplication1.Reserva.ReservaEnt entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaChannel : ConsoleApplication1.Reserva.IReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaClient : System.ServiceModel.ClientBase<ConsoleApplication1.Reserva.IReserva>, ConsoleApplication1.Reserva.IReserva {
        
        public ReservaClient() {
        }
        
        public ReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarReserva(ConsoleApplication1.Reserva.ReservaEnt entidad) {
            return base.Channel.InsertarReserva(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarReservaAsync(ConsoleApplication1.Reserva.ReservaEnt entidad) {
            return base.Channel.InsertarReservaAsync(entidad);
        }
        
        public ConsoleApplication1.Reserva.ReservaEnt MuestraDatoReserva(string c_esp) {
            return base.Channel.MuestraDatoReserva(c_esp);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.Reserva.ReservaEnt> MuestraDatoReservaAsync(string c_esp) {
            return base.Channel.MuestraDatoReservaAsync(c_esp);
        }
        
        public string MuestraListaTodasLasReservasRealizadas() {
            return base.Channel.MuestraListaTodasLasReservasRealizadas();
        }
        
        public System.Threading.Tasks.Task<string> MuestraListaTodasLasReservasRealizadasAsync() {
            return base.Channel.MuestraListaTodasLasReservasRealizadasAsync();
        }
        
        public string ListaTodosLosPacientesEnEspera() {
            return base.Channel.ListaTodosLosPacientesEnEspera();
        }
        
        public System.Threading.Tasks.Task<string> ListaTodosLosPacientesEnEsperaAsync() {
            return base.Channel.ListaTodosLosPacientesEnEsperaAsync();
        }
        
        public string MuestraPacientesEsperaXdoctor(string nombre) {
            return base.Channel.MuestraPacientesEsperaXdoctor(nombre);
        }
        
        public System.Threading.Tasks.Task<string> MuestraPacientesEsperaXdoctorAsync(string nombre) {
            return base.Channel.MuestraPacientesEsperaXdoctorAsync(nombre);
        }
        
        public string MuestraListaDeReservaXpaciente(string rut) {
            return base.Channel.MuestraListaDeReservaXpaciente(rut);
        }
        
        public System.Threading.Tasks.Task<string> MuestraListaDeReservaXpacienteAsync(string rut) {
            return base.Channel.MuestraListaDeReservaXpacienteAsync(rut);
        }
        
        public bool CambiarEstadoPaciente(ConsoleApplication1.Reserva.ReservaEnt entidad) {
            return base.Channel.CambiarEstadoPaciente(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarEstadoPacienteAsync(ConsoleApplication1.Reserva.ReservaEnt entidad) {
            return base.Channel.CambiarEstadoPacienteAsync(entidad);
        }
        
        public bool CambiarEstadoPacienteEspera(ConsoleApplication1.Reserva.ReservaEnt entidad) {
            return base.Channel.CambiarEstadoPacienteEspera(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarEstadoPacienteEsperaAsync(ConsoleApplication1.Reserva.ReservaEnt entidad) {
            return base.Channel.CambiarEstadoPacienteEsperaAsync(entidad);
        }
    }
}
