//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedicoWeb.PacienteSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteEnt", Namespace="http://schemas.datacontract.org/2004/07/CentroMedico.Datos")]
    [System.SerializableAttribute()]
    public partial class PacienteEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_apellido_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_apellido_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_fecha_nacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_previsionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_rutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paciente_telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_apellido_materno {
            get {
                return this.paciente_apellido_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_apellido_maternoField, value) != true)) {
                    this.paciente_apellido_maternoField = value;
                    this.RaisePropertyChanged("paciente_apellido_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_apellido_paterno {
            get {
                return this.paciente_apellido_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_apellido_paternoField, value) != true)) {
                    this.paciente_apellido_paternoField = value;
                    this.RaisePropertyChanged("paciente_apellido_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_clave {
            get {
                return this.paciente_claveField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_claveField, value) != true)) {
                    this.paciente_claveField = value;
                    this.RaisePropertyChanged("paciente_clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_direccion {
            get {
                return this.paciente_direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_direccionField, value) != true)) {
                    this.paciente_direccionField = value;
                    this.RaisePropertyChanged("paciente_direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_email {
            get {
                return this.paciente_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_emailField, value) != true)) {
                    this.paciente_emailField = value;
                    this.RaisePropertyChanged("paciente_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_fecha_nac {
            get {
                return this.paciente_fecha_nacField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_fecha_nacField, value) != true)) {
                    this.paciente_fecha_nacField = value;
                    this.RaisePropertyChanged("paciente_fecha_nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_id {
            get {
                return this.paciente_idField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_idField, value) != true)) {
                    this.paciente_idField = value;
                    this.RaisePropertyChanged("paciente_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_nombre {
            get {
                return this.paciente_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_nombreField, value) != true)) {
                    this.paciente_nombreField = value;
                    this.RaisePropertyChanged("paciente_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_prevision {
            get {
                return this.paciente_previsionField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_previsionField, value) != true)) {
                    this.paciente_previsionField = value;
                    this.RaisePropertyChanged("paciente_prevision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_rut {
            get {
                return this.paciente_rutField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_rutField, value) != true)) {
                    this.paciente_rutField = value;
                    this.RaisePropertyChanged("paciente_rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paciente_telefono {
            get {
                return this.paciente_telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.paciente_telefonoField, value) != true)) {
                    this.paciente_telefonoField = value;
                    this.RaisePropertyChanged("paciente_telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PacienteSvc.IPaciente")]
    public interface IPaciente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaciente/ValidarLoginPaciente", ReplyAction="http://tempuri.org/IPaciente/ValidarLoginPacienteResponse")]
        bool ValidarLoginPaciente(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaciente/ValidarLoginPaciente", ReplyAction="http://tempuri.org/IPaciente/ValidarLoginPacienteResponse")]
        System.Threading.Tasks.Task<bool> ValidarLoginPacienteAsync(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaciente/InsertarPaciente", ReplyAction="http://tempuri.org/IPaciente/InsertarPacienteResponse")]
        bool InsertarPaciente(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaciente/InsertarPaciente", ReplyAction="http://tempuri.org/IPaciente/InsertarPacienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarPacienteAsync(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaciente/ObtenerPaciente", ReplyAction="http://tempuri.org/IPaciente/ObtenerPacienteResponse")]
        string ObtenerPaciente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaciente/ObtenerPaciente", ReplyAction="http://tempuri.org/IPaciente/ObtenerPacienteResponse")]
        System.Threading.Tasks.Task<string> ObtenerPacienteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPacienteChannel : CentroMedicoWeb.PacienteSvc.IPaciente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacienteClient : System.ServiceModel.ClientBase<CentroMedicoWeb.PacienteSvc.IPaciente>, CentroMedicoWeb.PacienteSvc.IPaciente {
        
        public PacienteClient() {
        }
        
        public PacienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarLoginPaciente(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad) {
            return base.Channel.ValidarLoginPaciente(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarLoginPacienteAsync(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad) {
            return base.Channel.ValidarLoginPacienteAsync(entidad);
        }
        
        public bool InsertarPaciente(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad) {
            return base.Channel.InsertarPaciente(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarPacienteAsync(CentroMedicoWeb.PacienteSvc.PacienteEnt entidad) {
            return base.Channel.InsertarPacienteAsync(entidad);
        }
        
        public string ObtenerPaciente() {
            return base.Channel.ObtenerPaciente();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPacienteAsync() {
            return base.Channel.ObtenerPacienteAsync();
        }
    }
}
