//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Vista.SecretariaSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecretariaSvc.ISecretaria")]
    public interface ISecretaria {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerSecretariaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/ObtenerSecretaria", ReplyAction="http://tempuri.org/ISecretaria/ObtenerSecretariaResponse")]
        CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponse ObtenerSecretaria(CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/ObtenerSecretaria", ReplyAction="http://tempuri.org/ISecretaria/ObtenerSecretariaResponse")]
        System.Threading.Tasks.Task<CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponse> ObtenerSecretariaAsync(CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerSecretariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerSecretaria", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequestBody Body;
        
        public ObtenerSecretariaRequest() {
        }
        
        public ObtenerSecretariaRequest(CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerSecretariaRequestBody {
        
        public ObtenerSecretariaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerSecretariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerSecretariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponseBody Body;
        
        public ObtenerSecretariaResponse() {
        }
        
        public ObtenerSecretariaResponse(CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerSecretariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerSecretariaResult;
        
        public ObtenerSecretariaResponseBody() {
        }
        
        public ObtenerSecretariaResponseBody(string ObtenerSecretariaResult) {
            this.ObtenerSecretariaResult = ObtenerSecretariaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecretariaChannel : CentroMedico.Vista.SecretariaSvc.ISecretaria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecretariaClient : System.ServiceModel.ClientBase<CentroMedico.Vista.SecretariaSvc.ISecretaria>, CentroMedico.Vista.SecretariaSvc.ISecretaria {
        
        public SecretariaClient() {
        }
        
        public SecretariaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecretariaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretariaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretariaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponse CentroMedico.Vista.SecretariaSvc.ISecretaria.ObtenerSecretaria(CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest request) {
            return base.Channel.ObtenerSecretaria(request);
        }
        
        public string ObtenerSecretaria() {
            CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest inValue = new CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest();
            inValue.Body = new CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequestBody();
            CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponse retVal = ((CentroMedico.Vista.SecretariaSvc.ISecretaria)(this)).ObtenerSecretaria(inValue);
            return retVal.Body.ObtenerSecretariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponse> CentroMedico.Vista.SecretariaSvc.ISecretaria.ObtenerSecretariaAsync(CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest request) {
            return base.Channel.ObtenerSecretariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaResponse> ObtenerSecretariaAsync() {
            CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest inValue = new CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequest();
            inValue.Body = new CentroMedico.Vista.SecretariaSvc.ObtenerSecretariaRequestBody();
            return ((CentroMedico.Vista.SecretariaSvc.ISecretaria)(this)).ObtenerSecretariaAsync(inValue);
        }
    }
}
