//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Mvc.AgendaSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgendaEnt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AgendaEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_fecha_terminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agenda_medico_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string agenda_id {
            get {
                return this.agenda_idField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_idField, value) != true)) {
                    this.agenda_idField = value;
                    this.RaisePropertyChanged("agenda_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agenda_fecha_inicio {
            get {
                return this.agenda_fecha_inicioField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_fecha_inicioField, value) != true)) {
                    this.agenda_fecha_inicioField = value;
                    this.RaisePropertyChanged("agenda_fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string agenda_fecha_termino {
            get {
                return this.agenda_fecha_terminoField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_fecha_terminoField, value) != true)) {
                    this.agenda_fecha_terminoField = value;
                    this.RaisePropertyChanged("agenda_fecha_termino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string agenda_medico_id {
            get {
                return this.agenda_medico_idField;
            }
            set {
                if ((object.ReferenceEquals(this.agenda_medico_idField, value) != true)) {
                    this.agenda_medico_idField = value;
                    this.RaisePropertyChanged("agenda_medico_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgendaSvc.IAgenda")]
    public interface IAgenda {
        
        // CODEGEN: Generating message contract since element name ObtenerAgendaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/ObtenerAgenda", ReplyAction="http://tempuri.org/IAgenda/ObtenerAgendaResponse")]
        CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponse ObtenerAgenda(CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/ObtenerAgenda", ReplyAction="http://tempuri.org/IAgenda/ObtenerAgendaResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponse> ObtenerAgendaAsync(CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest request);
        
        // CODEGEN: Generating message contract since element name entidad from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/InsertarAgenda", ReplyAction="http://tempuri.org/IAgenda/InsertarAgendaResponse")]
        CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponse InsertarAgenda(CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/InsertarAgenda", ReplyAction="http://tempuri.org/IAgenda/InsertarAgendaResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponse> InsertarAgendaAsync(CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest request);
        
        // CODEGEN: Generating message contract since element name id_medico from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/ValidaDuplicidadAgendaGen", ReplyAction="http://tempuri.org/IAgenda/ValidaDuplicidadAgendaGenResponse")]
        CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponse ValidaDuplicidadAgendaGen(CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/ValidaDuplicidadAgendaGen", ReplyAction="http://tempuri.org/IAgenda/ValidaDuplicidadAgendaGenResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponse> ValidaDuplicidadAgendaGenAsync(CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest request);
        
        // CODEGEN: Generating message contract since element name id_medico from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/Trae_rangosAgendaGralXmedico", ReplyAction="http://tempuri.org/IAgenda/Trae_rangosAgendaGralXmedicoResponse")]
        CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponse Trae_rangosAgendaGralXmedico(CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenda/Trae_rangosAgendaGralXmedico", ReplyAction="http://tempuri.org/IAgenda/Trae_rangosAgendaGralXmedicoResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponse> Trae_rangosAgendaGralXmedicoAsync(CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAgendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAgenda", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequestBody Body;
        
        public ObtenerAgendaRequest() {
        }
        
        public ObtenerAgendaRequest(CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerAgendaRequestBody {
        
        public ObtenerAgendaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAgendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAgendaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponseBody Body;
        
        public ObtenerAgendaResponse() {
        }
        
        public ObtenerAgendaResponse(CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerAgendaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerAgendaResult;
        
        public ObtenerAgendaResponseBody() {
        }
        
        public ObtenerAgendaResponseBody(string ObtenerAgendaResult) {
            this.ObtenerAgendaResult = ObtenerAgendaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAgendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAgenda", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequestBody Body;
        
        public InsertarAgendaRequest() {
        }
        
        public InsertarAgendaRequest(CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAgendaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CentroMedico.Mvc.AgendaSvc.AgendaEnt entidad;
        
        public InsertarAgendaRequestBody() {
        }
        
        public InsertarAgendaRequestBody(CentroMedico.Mvc.AgendaSvc.AgendaEnt entidad) {
            this.entidad = entidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAgendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAgendaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponseBody Body;
        
        public InsertarAgendaResponse() {
        }
        
        public InsertarAgendaResponse(CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAgendaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarAgendaResult;
        
        public InsertarAgendaResponseBody() {
        }
        
        public InsertarAgendaResponseBody(bool InsertarAgendaResult) {
            this.InsertarAgendaResult = InsertarAgendaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaDuplicidadAgendaGenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaDuplicidadAgendaGen", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequestBody Body;
        
        public ValidaDuplicidadAgendaGenRequest() {
        }
        
        public ValidaDuplicidadAgendaGenRequest(CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaDuplicidadAgendaGenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_medico;
        
        public ValidaDuplicidadAgendaGenRequestBody() {
        }
        
        public ValidaDuplicidadAgendaGenRequestBody(string id_medico) {
            this.id_medico = id_medico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaDuplicidadAgendaGenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaDuplicidadAgendaGenResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponseBody Body;
        
        public ValidaDuplicidadAgendaGenResponse() {
        }
        
        public ValidaDuplicidadAgendaGenResponse(CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaDuplicidadAgendaGenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidaDuplicidadAgendaGenResult;
        
        public ValidaDuplicidadAgendaGenResponseBody() {
        }
        
        public ValidaDuplicidadAgendaGenResponseBody(bool ValidaDuplicidadAgendaGenResult) {
            this.ValidaDuplicidadAgendaGenResult = ValidaDuplicidadAgendaGenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trae_rangosAgendaGralXmedicoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Trae_rangosAgendaGralXmedico", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequestBody Body;
        
        public Trae_rangosAgendaGralXmedicoRequest() {
        }
        
        public Trae_rangosAgendaGralXmedicoRequest(CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Trae_rangosAgendaGralXmedicoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_medico;
        
        public Trae_rangosAgendaGralXmedicoRequestBody() {
        }
        
        public Trae_rangosAgendaGralXmedicoRequestBody(string id_medico) {
            this.id_medico = id_medico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Trae_rangosAgendaGralXmedicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Trae_rangosAgendaGralXmedicoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponseBody Body;
        
        public Trae_rangosAgendaGralXmedicoResponse() {
        }
        
        public Trae_rangosAgendaGralXmedicoResponse(CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Trae_rangosAgendaGralXmedicoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CentroMedico.Mvc.AgendaSvc.AgendaEnt Trae_rangosAgendaGralXmedicoResult;
        
        public Trae_rangosAgendaGralXmedicoResponseBody() {
        }
        
        public Trae_rangosAgendaGralXmedicoResponseBody(CentroMedico.Mvc.AgendaSvc.AgendaEnt Trae_rangosAgendaGralXmedicoResult) {
            this.Trae_rangosAgendaGralXmedicoResult = Trae_rangosAgendaGralXmedicoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgendaChannel : CentroMedico.Mvc.AgendaSvc.IAgenda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgendaClient : System.ServiceModel.ClientBase<CentroMedico.Mvc.AgendaSvc.IAgenda>, CentroMedico.Mvc.AgendaSvc.IAgenda {
        
        public AgendaClient() {
        }
        
        public AgendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponse CentroMedico.Mvc.AgendaSvc.IAgenda.ObtenerAgenda(CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest request) {
            return base.Channel.ObtenerAgenda(request);
        }
        
        public string ObtenerAgenda() {
            CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest inValue = new CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequestBody();
            CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponse retVal = ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).ObtenerAgenda(inValue);
            return retVal.Body.ObtenerAgendaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponse> CentroMedico.Mvc.AgendaSvc.IAgenda.ObtenerAgendaAsync(CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest request) {
            return base.Channel.ObtenerAgendaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.ObtenerAgendaResponse> ObtenerAgendaAsync() {
            CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest inValue = new CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.ObtenerAgendaRequestBody();
            return ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).ObtenerAgendaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponse CentroMedico.Mvc.AgendaSvc.IAgenda.InsertarAgenda(CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest request) {
            return base.Channel.InsertarAgenda(request);
        }
        
        public bool InsertarAgenda(CentroMedico.Mvc.AgendaSvc.AgendaEnt entidad) {
            CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest inValue = new CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequestBody();
            inValue.Body.entidad = entidad;
            CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponse retVal = ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).InsertarAgenda(inValue);
            return retVal.Body.InsertarAgendaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponse> CentroMedico.Mvc.AgendaSvc.IAgenda.InsertarAgendaAsync(CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest request) {
            return base.Channel.InsertarAgendaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.InsertarAgendaResponse> InsertarAgendaAsync(CentroMedico.Mvc.AgendaSvc.AgendaEnt entidad) {
            CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest inValue = new CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.InsertarAgendaRequestBody();
            inValue.Body.entidad = entidad;
            return ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).InsertarAgendaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponse CentroMedico.Mvc.AgendaSvc.IAgenda.ValidaDuplicidadAgendaGen(CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest request) {
            return base.Channel.ValidaDuplicidadAgendaGen(request);
        }
        
        public bool ValidaDuplicidadAgendaGen(string id_medico) {
            CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest inValue = new CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequestBody();
            inValue.Body.id_medico = id_medico;
            CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponse retVal = ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).ValidaDuplicidadAgendaGen(inValue);
            return retVal.Body.ValidaDuplicidadAgendaGenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponse> CentroMedico.Mvc.AgendaSvc.IAgenda.ValidaDuplicidadAgendaGenAsync(CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest request) {
            return base.Channel.ValidaDuplicidadAgendaGenAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenResponse> ValidaDuplicidadAgendaGenAsync(string id_medico) {
            CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest inValue = new CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.ValidaDuplicidadAgendaGenRequestBody();
            inValue.Body.id_medico = id_medico;
            return ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).ValidaDuplicidadAgendaGenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponse CentroMedico.Mvc.AgendaSvc.IAgenda.Trae_rangosAgendaGralXmedico(CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest request) {
            return base.Channel.Trae_rangosAgendaGralXmedico(request);
        }
        
        public CentroMedico.Mvc.AgendaSvc.AgendaEnt Trae_rangosAgendaGralXmedico(string id_medico) {
            CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest inValue = new CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequestBody();
            inValue.Body.id_medico = id_medico;
            CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponse retVal = ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).Trae_rangosAgendaGralXmedico(inValue);
            return retVal.Body.Trae_rangosAgendaGralXmedicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponse> CentroMedico.Mvc.AgendaSvc.IAgenda.Trae_rangosAgendaGralXmedicoAsync(CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest request) {
            return base.Channel.Trae_rangosAgendaGralXmedicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoResponse> Trae_rangosAgendaGralXmedicoAsync(string id_medico) {
            CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest inValue = new CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequest();
            inValue.Body = new CentroMedico.Mvc.AgendaSvc.Trae_rangosAgendaGralXmedicoRequestBody();
            inValue.Body.id_medico = id_medico;
            return ((CentroMedico.Mvc.AgendaSvc.IAgenda)(this)).Trae_rangosAgendaGralXmedicoAsync(inValue);
        }
    }
}
