//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Mvc.EstadoReservaSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadoReservaSvc.IEstadoReserva")]
    public interface IEstadoReserva {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerEstadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoReserva/ObtenerEstado", ReplyAction="http://tempuri.org/IEstadoReserva/ObtenerEstadoResponse")]
        CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponse ObtenerEstado(CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoReserva/ObtenerEstado", ReplyAction="http://tempuri.org/IEstadoReserva/ObtenerEstadoResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponse> ObtenerEstadoAsync(CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEstado", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequestBody Body;
        
        public ObtenerEstadoRequest() {
        }
        
        public ObtenerEstadoRequest(CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerEstadoRequestBody {
        
        public ObtenerEstadoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEstadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponseBody Body;
        
        public ObtenerEstadoResponse() {
        }
        
        public ObtenerEstadoResponse(CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEstadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerEstadoResult;
        
        public ObtenerEstadoResponseBody() {
        }
        
        public ObtenerEstadoResponseBody(string ObtenerEstadoResult) {
            this.ObtenerEstadoResult = ObtenerEstadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstadoReservaChannel : CentroMedico.Mvc.EstadoReservaSvc.IEstadoReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoReservaClient : System.ServiceModel.ClientBase<CentroMedico.Mvc.EstadoReservaSvc.IEstadoReserva>, CentroMedico.Mvc.EstadoReservaSvc.IEstadoReserva {
        
        public EstadoReservaClient() {
        }
        
        public EstadoReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadoReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponse CentroMedico.Mvc.EstadoReservaSvc.IEstadoReserva.ObtenerEstado(CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest request) {
            return base.Channel.ObtenerEstado(request);
        }
        
        public string ObtenerEstado() {
            CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest inValue = new CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest();
            inValue.Body = new CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequestBody();
            CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponse retVal = ((CentroMedico.Mvc.EstadoReservaSvc.IEstadoReserva)(this)).ObtenerEstado(inValue);
            return retVal.Body.ObtenerEstadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponse> CentroMedico.Mvc.EstadoReservaSvc.IEstadoReserva.ObtenerEstadoAsync(CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest request) {
            return base.Channel.ObtenerEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoResponse> ObtenerEstadoAsync() {
            CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest inValue = new CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequest();
            inValue.Body = new CentroMedico.Mvc.EstadoReservaSvc.ObtenerEstadoRequestBody();
            return ((CentroMedico.Mvc.EstadoReservaSvc.IEstadoReserva)(this)).ObtenerEstadoAsync(inValue);
        }
    }
}
