//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Mvc.EspecialidadSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EspecialidadSvc.IEspecialidad")]
    public interface IEspecialidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspecialidad/InsertarEspecialidad", ReplyAction="http://tempuri.org/IEspecialidad/InsertarEspecialidadResponse")]
        bool InsertarEspecialidad(CentroMedico.Datos.EspecialidadEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspecialidad/InsertarEspecialidad", ReplyAction="http://tempuri.org/IEspecialidad/InsertarEspecialidadResponse")]
        System.Threading.Tasks.Task<bool> InsertarEspecialidadAsync(CentroMedico.Datos.EspecialidadEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspecialidad/ObtenerEspecialidad", ReplyAction="http://tempuri.org/IEspecialidad/ObtenerEspecialidadResponse")]
        string ObtenerEspecialidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspecialidad/ObtenerEspecialidad", ReplyAction="http://tempuri.org/IEspecialidad/ObtenerEspecialidadResponse")]
        System.Threading.Tasks.Task<string> ObtenerEspecialidadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEspecialidadChannel : CentroMedico.Mvc.EspecialidadSvc.IEspecialidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EspecialidadClient : System.ServiceModel.ClientBase<CentroMedico.Mvc.EspecialidadSvc.IEspecialidad>, CentroMedico.Mvc.EspecialidadSvc.IEspecialidad {
        
        public EspecialidadClient() {
        }
        
        public EspecialidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EspecialidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EspecialidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EspecialidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarEspecialidad(CentroMedico.Datos.EspecialidadEnt entidad) {
            return base.Channel.InsertarEspecialidad(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarEspecialidadAsync(CentroMedico.Datos.EspecialidadEnt entidad) {
            return base.Channel.InsertarEspecialidadAsync(entidad);
        }
        
        public string ObtenerEspecialidad() {
            return base.Channel.ObtenerEspecialidad();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerEspecialidadAsync() {
            return base.Channel.ObtenerEspecialidadAsync();
        }
    }
}
