//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedico.Mvc.SecretariaSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecretariaEnt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SecretariaEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secretaria_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secretaria_rutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secretaria_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secretaria_apellido_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secretaria_apellido_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secretaria_claveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secretaria_emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string secretaria_id {
            get {
                return this.secretaria_idField;
            }
            set {
                if ((object.ReferenceEquals(this.secretaria_idField, value) != true)) {
                    this.secretaria_idField = value;
                    this.RaisePropertyChanged("secretaria_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string secretaria_rut {
            get {
                return this.secretaria_rutField;
            }
            set {
                if ((object.ReferenceEquals(this.secretaria_rutField, value) != true)) {
                    this.secretaria_rutField = value;
                    this.RaisePropertyChanged("secretaria_rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string secretaria_nombre {
            get {
                return this.secretaria_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.secretaria_nombreField, value) != true)) {
                    this.secretaria_nombreField = value;
                    this.RaisePropertyChanged("secretaria_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string secretaria_apellido_paterno {
            get {
                return this.secretaria_apellido_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.secretaria_apellido_paternoField, value) != true)) {
                    this.secretaria_apellido_paternoField = value;
                    this.RaisePropertyChanged("secretaria_apellido_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string secretaria_apellido_materno {
            get {
                return this.secretaria_apellido_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.secretaria_apellido_maternoField, value) != true)) {
                    this.secretaria_apellido_maternoField = value;
                    this.RaisePropertyChanged("secretaria_apellido_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string secretaria_clave {
            get {
                return this.secretaria_claveField;
            }
            set {
                if ((object.ReferenceEquals(this.secretaria_claveField, value) != true)) {
                    this.secretaria_claveField = value;
                    this.RaisePropertyChanged("secretaria_clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string secretaria_email {
            get {
                return this.secretaria_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.secretaria_emailField, value) != true)) {
                    this.secretaria_emailField = value;
                    this.RaisePropertyChanged("secretaria_email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecretariaSvc.ISecretaria")]
    public interface ISecretaria {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento entidad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/ValidarLoginSecretaria", ReplyAction="http://tempuri.org/ISecretaria/ValidarLoginSecretariaResponse")]
        CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponse ValidarLoginSecretaria(CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/ValidarLoginSecretaria", ReplyAction="http://tempuri.org/ISecretaria/ValidarLoginSecretariaResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponse> ValidarLoginSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento entidad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/InsertarSecretaria", ReplyAction="http://tempuri.org/ISecretaria/InsertarSecretariaResponse")]
        CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponse InsertarSecretaria(CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/InsertarSecretaria", ReplyAction="http://tempuri.org/ISecretaria/InsertarSecretariaResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponse> InsertarSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento entidad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/ValidaDuplicidadSecretaria", ReplyAction="http://tempuri.org/ISecretaria/ValidaDuplicidadSecretariaResponse")]
        CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponse ValidaDuplicidadSecretaria(CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecretaria/ValidaDuplicidadSecretaria", ReplyAction="http://tempuri.org/ISecretaria/ValidaDuplicidadSecretariaResponse")]
        System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponse> ValidaDuplicidadSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarLoginSecretariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarLoginSecretaria", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequestBody Body;
        
        public ValidarLoginSecretariaRequest() {
        }
        
        public ValidarLoginSecretariaRequest(CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarLoginSecretariaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad;
        
        public ValidarLoginSecretariaRequestBody() {
        }
        
        public ValidarLoginSecretariaRequestBody(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            this.entidad = entidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarLoginSecretariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarLoginSecretariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponseBody Body;
        
        public ValidarLoginSecretariaResponse() {
        }
        
        public ValidarLoginSecretariaResponse(CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarLoginSecretariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidarLoginSecretariaResult;
        
        public ValidarLoginSecretariaResponseBody() {
        }
        
        public ValidarLoginSecretariaResponseBody(bool ValidarLoginSecretariaResult) {
            this.ValidarLoginSecretariaResult = ValidarLoginSecretariaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarSecretariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarSecretaria", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequestBody Body;
        
        public InsertarSecretariaRequest() {
        }
        
        public InsertarSecretariaRequest(CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarSecretariaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad;
        
        public InsertarSecretariaRequestBody() {
        }
        
        public InsertarSecretariaRequestBody(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            this.entidad = entidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarSecretariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarSecretariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponseBody Body;
        
        public InsertarSecretariaResponse() {
        }
        
        public InsertarSecretariaResponse(CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarSecretariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarSecretariaResult;
        
        public InsertarSecretariaResponseBody() {
        }
        
        public InsertarSecretariaResponseBody(bool InsertarSecretariaResult) {
            this.InsertarSecretariaResult = InsertarSecretariaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaDuplicidadSecretariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaDuplicidadSecretaria", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequestBody Body;
        
        public ValidaDuplicidadSecretariaRequest() {
        }
        
        public ValidaDuplicidadSecretariaRequest(CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaDuplicidadSecretariaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad;
        
        public ValidaDuplicidadSecretariaRequestBody() {
        }
        
        public ValidaDuplicidadSecretariaRequestBody(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            this.entidad = entidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidaDuplicidadSecretariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidaDuplicidadSecretariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponseBody Body;
        
        public ValidaDuplicidadSecretariaResponse() {
        }
        
        public ValidaDuplicidadSecretariaResponse(CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidaDuplicidadSecretariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidaDuplicidadSecretariaResult;
        
        public ValidaDuplicidadSecretariaResponseBody() {
        }
        
        public ValidaDuplicidadSecretariaResponseBody(bool ValidaDuplicidadSecretariaResult) {
            this.ValidaDuplicidadSecretariaResult = ValidaDuplicidadSecretariaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecretariaChannel : CentroMedico.Mvc.SecretariaSvc.ISecretaria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecretariaClient : System.ServiceModel.ClientBase<CentroMedico.Mvc.SecretariaSvc.ISecretaria>, CentroMedico.Mvc.SecretariaSvc.ISecretaria {
        
        public SecretariaClient() {
        }
        
        public SecretariaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecretariaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretariaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecretariaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponse CentroMedico.Mvc.SecretariaSvc.ISecretaria.ValidarLoginSecretaria(CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest request) {
            return base.Channel.ValidarLoginSecretaria(request);
        }
        
        public bool ValidarLoginSecretaria(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest inValue = new CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest();
            inValue.Body = new CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequestBody();
            inValue.Body.entidad = entidad;
            CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponse retVal = ((CentroMedico.Mvc.SecretariaSvc.ISecretaria)(this)).ValidarLoginSecretaria(inValue);
            return retVal.Body.ValidarLoginSecretariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponse> CentroMedico.Mvc.SecretariaSvc.ISecretaria.ValidarLoginSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest request) {
            return base.Channel.ValidarLoginSecretariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaResponse> ValidarLoginSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest inValue = new CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequest();
            inValue.Body = new CentroMedico.Mvc.SecretariaSvc.ValidarLoginSecretariaRequestBody();
            inValue.Body.entidad = entidad;
            return ((CentroMedico.Mvc.SecretariaSvc.ISecretaria)(this)).ValidarLoginSecretariaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponse CentroMedico.Mvc.SecretariaSvc.ISecretaria.InsertarSecretaria(CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest request) {
            return base.Channel.InsertarSecretaria(request);
        }
        
        public bool InsertarSecretaria(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest inValue = new CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest();
            inValue.Body = new CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequestBody();
            inValue.Body.entidad = entidad;
            CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponse retVal = ((CentroMedico.Mvc.SecretariaSvc.ISecretaria)(this)).InsertarSecretaria(inValue);
            return retVal.Body.InsertarSecretariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponse> CentroMedico.Mvc.SecretariaSvc.ISecretaria.InsertarSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest request) {
            return base.Channel.InsertarSecretariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaResponse> InsertarSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest inValue = new CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequest();
            inValue.Body = new CentroMedico.Mvc.SecretariaSvc.InsertarSecretariaRequestBody();
            inValue.Body.entidad = entidad;
            return ((CentroMedico.Mvc.SecretariaSvc.ISecretaria)(this)).InsertarSecretariaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponse CentroMedico.Mvc.SecretariaSvc.ISecretaria.ValidaDuplicidadSecretaria(CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest request) {
            return base.Channel.ValidaDuplicidadSecretaria(request);
        }
        
        public bool ValidaDuplicidadSecretaria(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest inValue = new CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest();
            inValue.Body = new CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequestBody();
            inValue.Body.entidad = entidad;
            CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponse retVal = ((CentroMedico.Mvc.SecretariaSvc.ISecretaria)(this)).ValidaDuplicidadSecretaria(inValue);
            return retVal.Body.ValidaDuplicidadSecretariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponse> CentroMedico.Mvc.SecretariaSvc.ISecretaria.ValidaDuplicidadSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest request) {
            return base.Channel.ValidaDuplicidadSecretariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaResponse> ValidaDuplicidadSecretariaAsync(CentroMedico.Mvc.SecretariaSvc.SecretariaEnt entidad) {
            CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest inValue = new CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequest();
            inValue.Body = new CentroMedico.Mvc.SecretariaSvc.ValidaDuplicidadSecretariaRequestBody();
            inValue.Body.entidad = entidad;
            return ((CentroMedico.Mvc.SecretariaSvc.ISecretaria)(this)).ValidaDuplicidadSecretariaAsync(inValue);
        }
    }
}
