//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.SucursalSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SucursalEnt", Namespace="http://schemas.datacontract.org/2004/07/CentroMedico.Datos")]
    [System.SerializableAttribute()]
    public partial class SucursalEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sucursal_direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sucursal_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sucursal_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sucursal_telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sucursal_direccion {
            get {
                return this.sucursal_direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.sucursal_direccionField, value) != true)) {
                    this.sucursal_direccionField = value;
                    this.RaisePropertyChanged("sucursal_direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sucursal_id {
            get {
                return this.sucursal_idField;
            }
            set {
                if ((object.ReferenceEquals(this.sucursal_idField, value) != true)) {
                    this.sucursal_idField = value;
                    this.RaisePropertyChanged("sucursal_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sucursal_nombre {
            get {
                return this.sucursal_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.sucursal_nombreField, value) != true)) {
                    this.sucursal_nombreField = value;
                    this.RaisePropertyChanged("sucursal_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sucursal_telefono {
            get {
                return this.sucursal_telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.sucursal_telefonoField, value) != true)) {
                    this.sucursal_telefonoField = value;
                    this.RaisePropertyChanged("sucursal_telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SucursalSvc.ISucursales")]
    public interface ISucursales {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/ObtenerSucursales", ReplyAction="http://tempuri.org/ISucursales/ObtenerSucursalesResponse")]
        string ObtenerSucursales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/ObtenerSucursales", ReplyAction="http://tempuri.org/ISucursales/ObtenerSucursalesResponse")]
        System.Threading.Tasks.Task<string> ObtenerSucursalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/InsertarSucursal", ReplyAction="http://tempuri.org/ISucursales/InsertarSucursalResponse")]
        bool InsertarSucursal(ConsoleApplication1.SucursalSvc.SucursalEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursales/InsertarSucursal", ReplyAction="http://tempuri.org/ISucursales/InsertarSucursalResponse")]
        System.Threading.Tasks.Task<bool> InsertarSucursalAsync(ConsoleApplication1.SucursalSvc.SucursalEnt entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISucursalesChannel : ConsoleApplication1.SucursalSvc.ISucursales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SucursalesClient : System.ServiceModel.ClientBase<ConsoleApplication1.SucursalSvc.ISucursales>, ConsoleApplication1.SucursalSvc.ISucursales {
        
        public SucursalesClient() {
        }
        
        public SucursalesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SucursalesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SucursalesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SucursalesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerSucursales() {
            return base.Channel.ObtenerSucursales();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerSucursalesAsync() {
            return base.Channel.ObtenerSucursalesAsync();
        }
        
        public bool InsertarSucursal(ConsoleApplication1.SucursalSvc.SucursalEnt entidad) {
            return base.Channel.InsertarSucursal(entidad);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarSucursalAsync(ConsoleApplication1.SucursalSvc.SucursalEnt entidad) {
            return base.Channel.InsertarSucursalAsync(entidad);
        }
    }
}
