//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroMedicoWeb.AgendiaDiariaSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgendaDiariaEnt", Namespace="http://schemas.datacontract.org/2004/07/CentroMedico.Datos")]
    [System.SerializableAttribute()]
    public partial class AgendaDiariaEnt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGENDA_DETALLE_ACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGENDA_DETALLE_AGENDA_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGENDA_DETALLE_DIA_ATENCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGENDA_DETALLE_HORA_MEDICAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGENDA_DETALLE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AGENDA_DETALLE_MEDICO_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGENDA_DETALLE_ACTIVO {
            get {
                return this.AGENDA_DETALLE_ACTIVOField;
            }
            set {
                if ((object.ReferenceEquals(this.AGENDA_DETALLE_ACTIVOField, value) != true)) {
                    this.AGENDA_DETALLE_ACTIVOField = value;
                    this.RaisePropertyChanged("AGENDA_DETALLE_ACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGENDA_DETALLE_AGENDA_ID {
            get {
                return this.AGENDA_DETALLE_AGENDA_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.AGENDA_DETALLE_AGENDA_IDField, value) != true)) {
                    this.AGENDA_DETALLE_AGENDA_IDField = value;
                    this.RaisePropertyChanged("AGENDA_DETALLE_AGENDA_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGENDA_DETALLE_DIA_ATENCION {
            get {
                return this.AGENDA_DETALLE_DIA_ATENCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.AGENDA_DETALLE_DIA_ATENCIONField, value) != true)) {
                    this.AGENDA_DETALLE_DIA_ATENCIONField = value;
                    this.RaisePropertyChanged("AGENDA_DETALLE_DIA_ATENCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGENDA_DETALLE_HORA_MEDICA {
            get {
                return this.AGENDA_DETALLE_HORA_MEDICAField;
            }
            set {
                if ((object.ReferenceEquals(this.AGENDA_DETALLE_HORA_MEDICAField, value) != true)) {
                    this.AGENDA_DETALLE_HORA_MEDICAField = value;
                    this.RaisePropertyChanged("AGENDA_DETALLE_HORA_MEDICA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGENDA_DETALLE_ID {
            get {
                return this.AGENDA_DETALLE_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.AGENDA_DETALLE_IDField, value) != true)) {
                    this.AGENDA_DETALLE_IDField = value;
                    this.RaisePropertyChanged("AGENDA_DETALLE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AGENDA_DETALLE_MEDICO_ID {
            get {
                return this.AGENDA_DETALLE_MEDICO_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.AGENDA_DETALLE_MEDICO_IDField, value) != true)) {
                    this.AGENDA_DETALLE_MEDICO_IDField = value;
                    this.RaisePropertyChanged("AGENDA_DETALLE_MEDICO_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgendiaDiariaSvc.IAgendaDiariasvc")]
    public interface IAgendaDiariasvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaDiariasvc/InsertarAgendaDiaria", ReplyAction="http://tempuri.org/IAgendaDiariasvc/InsertarAgendaDiariaResponse")]
        bool InsertarAgendaDiaria(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaDiariasvc/InsertarAgendaDiaria", ReplyAction="http://tempuri.org/IAgendaDiariasvc/InsertarAgendaDiariaResponse")]
        System.Threading.Tasks.Task<bool> InsertarAgendaDiariaAsync(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaDiariasvc/EditarAgendaDiaria", ReplyAction="http://tempuri.org/IAgendaDiariasvc/EditarAgendaDiariaResponse")]
        bool EditarAgendaDiaria(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaDiariasvc/EditarAgendaDiaria", ReplyAction="http://tempuri.org/IAgendaDiariasvc/EditarAgendaDiariaResponse")]
        System.Threading.Tasks.Task<bool> EditarAgendaDiariaAsync(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaDiariasvc/ObtenerCalendario", ReplyAction="http://tempuri.org/IAgendaDiariasvc/ObtenerCalendarioResponse")]
        string ObtenerCalendario(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgendaDiariasvc/ObtenerCalendario", ReplyAction="http://tempuri.org/IAgendaDiariasvc/ObtenerCalendarioResponse")]
        System.Threading.Tasks.Task<string> ObtenerCalendarioAsync(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgendaDiariasvcChannel : CentroMedicoWeb.AgendiaDiariaSvc.IAgendaDiariasvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgendaDiariasvcClient : System.ServiceModel.ClientBase<CentroMedicoWeb.AgendiaDiariaSvc.IAgendaDiariasvc>, CentroMedicoWeb.AgendiaDiariaSvc.IAgendaDiariasvc {
        
        public AgendaDiariasvcClient() {
        }
        
        public AgendaDiariasvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgendaDiariasvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaDiariasvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgendaDiariasvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarAgendaDiaria(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion) {
            return base.Channel.InsertarAgendaDiaria(entidad, hora_inicio, hora_termino, duracion);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAgendaDiariaAsync(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion) {
            return base.Channel.InsertarAgendaDiariaAsync(entidad, hora_inicio, hora_termino, duracion);
        }
        
        public bool EditarAgendaDiaria(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion) {
            return base.Channel.EditarAgendaDiaria(entidad, hora_inicio, hora_termino, duracion);
        }
        
        public System.Threading.Tasks.Task<bool> EditarAgendaDiariaAsync(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad, string hora_inicio, string hora_termino, string duracion) {
            return base.Channel.EditarAgendaDiariaAsync(entidad, hora_inicio, hora_termino, duracion);
        }
        
        public string ObtenerCalendario(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad) {
            return base.Channel.ObtenerCalendario(entidad);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerCalendarioAsync(CentroMedicoWeb.AgendiaDiariaSvc.AgendaDiariaEnt entidad) {
            return base.Channel.ObtenerCalendarioAsync(entidad);
        }
    }
}
